@url = https://atividade-final.vercel.app
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzOGZmMmYwOGM3MWVkYWIyZDc2Mjg4NiIsImlhdCI6MTY3MDM3ODIzOH0.G2D4NeRQCzyeeoMt41dW0t3JQiF1tsn31C7akQT6yn8

// Criar Usuario
POST {{url}}/usuario/cadastrar
content-type: application/json

{
  "email": "lucas@gmail.com",
  "nome": "lucas",
  "senha": "lucas"
}

###

// Fazer login
POST {{url}}/usuario/login
content-type: application/json

{
  "email": "lucas@gmail.com",
  "senha": "lucas"
}

###

// Ver todas as petições
GET {{url}}/peticoes

###

// Criar petição
POST {{url}}/peticoes/criar
Content-Type: application/json
Authorization: token {{token}}

{
  "titulo": "titulo peticao 6",
  "descricao": "descricao peticao 2",
  "foto": "link peticao 2"
}

###

// Assinar Petição
POST {{url}}/peticoes/assinar/638ff3178c71edab2d762887
Authorization: token {{token}}

###

// Excluir Petição
DELETE {{url}}/peticoes/deletar/638fd34557430158062722bc
Authorization: token {{token}}

###

// Deletar todas as minhas petições
DELETE {{url}}/peticoes/deletartudo
Authorization: token {{token}}
